# Exported from Render on 2026-01-21T23:23:45Z
version: "1"
projects:
- name: SentencingAnalysis
  environments:
  - name: Production
    services:
    - type: web
      name: PgHero-dpg-d5o27kt6ubrc73f7nlfg-a
      runtime: image
      image:
        url: docker.io/ankane/pghero:latest
      plan: free
      envVars:
      - key: WEB_CONCURRENCY
        sync: false
      - key: PGHERO_PASSWORD
        sync: false
      - key: PGHERO_USERNAME
        sync: false
      - key: DATABASE_URL
        sync: false
      region: oregon
      autoDeployTrigger: commit
    - type: worker
      name: sentencinganalysis
      runtime: docker
      repo: https://github.com/carbidethegreate/sentencinganalysis
      plan: starter
      region: oregon
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
    - type: web
      name: sentencinganalysis_python_3
      runtime: python
      repo: https://github.com/carbidethegreate/sentencinganalysis
      plan: standard
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn --bind 0.0.0.0:${PORT:-5000} --timeout ${GUNICORN_TIMEOUT:-180} "app:create_app()"
      autoDeployTrigger: commit
    - type: pserv
      name: sentencinganalysis
      runtime: docker
      repo: https://github.com/carbidethegreate/sentencinganalysis
      plan: starter
      envVars:
      - key: Username
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: Port
        sync: false
      - key: Password
        sync: false
      - key: PSQLCommand
        sync: false
      - key: OpenAPIKey
        sync: false
      - key: InternalDatabaseURL
        sync: false
      - key: Hostname
        fromDatabase:
          name: FSD
          property: host
      - key: GoogleSheetsAPIKey
        sync: false
      - key: GithubAPIKey
        sync: false
      - key: ExternalDatabaseURL
        sync: false
      - key: Database
        sync: false
      - key: CPD_ADMIN_KEY
        sync: false
      region: oregon
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
    - type: pserv
      name: sentencinganalysis_pserv
      runtime: docker
      repo: https://github.com/carbidethegreate/sentencinganalysis
      plan: starter
      envVars:
      - key: CPD_ADMIN_KEY
        sync: false
      - key: Database
        sync: false
      - key: ExternalDatabaseURL
        sync: false
      - key: GithubAPIKey
        sync: false
      - key: GoogleSheetsAPIKey
        sync: false
      - key: OpenAPIKey
        sync: false
      - key: PSQLCommand
        sync: false
      - key: Port
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: Username
        sync: false
      - key: Hostname
        fromDatabase:
          name: FSD
          property: host
      - key: InternalDatabaseURL
        sync: false
      - key: Password
        sync: false
      region: oregon
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
    - type: web
      name: pgAdmin-dpg-d5o27kt6ubrc73f7nlfg-a
      runtime: docker
      repo: https://github.com/render-examples/pgadmin
      plan: pro
      envVars:
      - key: servers.json
        sync: false
      - key: pgpassfile
        sync: false
      - key: PORT
        sync: false
      - key: PGADMIN_SERVER_JSON_FILE
        sync: false
      - key: PGADMIN_LISTEN_PORT
        sync: false
      - key: PGADMIN_DEFAULT_PASSWORD
        sync: false
      - key: PGADMIN_DEFAULT_EMAIL
        sync: false
      - key: PGADMIN_DATABASE_USER
        sync: false
      - key: PGADMIN_DATABASE_NAME
        sync: false
      - key: PGADMIN_DATABASE_HOST
        fromDatabase:
          name: FSD
          property: host
      - key: GUNICORN_THREADS
        sync: false
      region: oregon
      dockerContext: .
      dockerfilePath: ./Dockerfile
      disk:
        name: pgadmin
        mountPath: /var/lib/pgadmin
        sizeGB: 1
      autoDeployTrigger: commit
    - type: web
      name: CourtDataPro
      runtime: docker
      repo: https://github.com/carbidethegreate/sentencinganalysis
      plan: pro
      envVars:
      - fromGroup: sentencinganalysis-env
      region: oregon
      dockerContext: .
      dockerfilePath: ./Dockerfile
      domains:
      - www.courtdatapro.com
      - courtdatapro.com
      autoDeployTrigger: commit
    - type: cron
      name: sentencinganalysis_dockerfile_cron_job
      runtime: docker
      repo: https://github.com/carbidethegreate/sentencinganalysis
      plan: starter
      region: oregon
      schedule: '*/5 * * * *'
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
    databases:
    - name: FSD
      databaseName: fsd_oe4w
      user: fsd_c9x2_user
      plan: pro-4gb
      region: oregon
      ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
      postgresMajorVersion: "18"
      diskSizeGB: 100
